import uuid
from sqlmodel import SQLModel, Field


class Drink(SQLModel, table = True):
    id: uuid.UUID = Field(default_factory = uuid.uuid4, primary_key = True)
    instruction: str = Field(index = True)
    name: str = Field(index = True)
    category:str = Field(index = True)
    glass : str = Field(index = True)
    image: str = Field(index = True)
    integrate1: str = Field(index = True)
    integrate2: str = Field(index = True)
    integrate3: str = Field(index = True)
    integrate4: str = Field(index = True)
    integrate5: str = Field(index = True)
    integrate6: str = Field(index = True)
    integrate7: str = Field(index = True)
    integrate8: str = Field(index = True)
    integrate9: str = Field(index = True)
    integrate10: str = Field(index = True)
    integrate11: str = Field(index = True)
    integrate12: str = Field(index = True)
    integrate13: str = Field(index = True)
    integrate14: str = Field(index = True)
    integrate15: str = Field(index = True)
    mesure1: str = Field(index = True)
    mesure2: str = Field(index = True)
    mesure3: str = Field(index = True)
    mesure4: str = Field(index = True)
    mesure5: str = Field(index = True)
    mesure6: str = Field(index = True)
    mesure7: str = Field(index = True)
    mesure8: str = Field(index = True)
    mesure9: str = Field(index = True)
    mesure10: str = Field(index = True)
    mesure11: str = Field(index = True)
    mesure12: str = Field(index = True)
    mesure13: str = Field(index = True)
    mesure14: str = Field(index = True)
    mesure15: str = Field(index = True)
    alkoholic: bool = Field(index =True)